### ISSUE TITLE
Adding the "Shaders (Engine)" folder automatically should be optional

### ISSUE THREAD

**Issue by douglaslassance** [hellokenlee/SublimeUnrealShader#1]
The feature that "automatically opens the whole engine shader folder when opening *.ush and *.usf files that located in engine folder" should be optional. The fact that it keeps on changing the `.sublime-project` is problematic for me.

**Comment by hellokenlee** [comment]
Sure, now you can change this behavior in UnrealShader.sublime-settings since v[1.0.9](https://github.com/hellokenlee/SublimeUnrealShader/releases/tag/1.0.9).

**Comment by douglaslassance** [comment]
Thanks, that worked. Just so you are aware, that setting file does not seem to come in when you install using Sublime Package Manager.
